name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                submodules: true

            - name: Setup Python
              uses: actions/setup-python@v3

            - name: Install dependencies
              run: |
                apt update
                apt install -y ocl-icd-opencl-dev opencl-headers
                pip install -r requirements.txt

            - name: Benchmark
              run: |
                python Benchmark.py