name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: [self-hosted, Linux, X64]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5

            - name: Setup Virtual Environment
              run: |
                python3 -m venv .venv
                . .vevn/bin/activate

            - name: Install dependencies
              run: |
                pip install -r requirements.txt

            - name: Benchmark
              run: |
                python Benchmark.py
